import type { Metadata } from 'next';

import { siteConfig } from '@/config/site';

export const absoluteUrl = (path = '/') => new URL(path, siteConfig.url).toString();

interface PageMetadataInput {
  /** Full <title>. Pass the complete string; the site name is NOT appended. */
  title: string;
  description: string;
  /** Path starting with "/", used for the canonical URL and og:url. */
  path: string;
  type?: 'website' | 'article';
}

/**
 * Builds a page's Metadata with canonical, Open Graph and Twitter tags.
 * Next merges metadata shallowly, so every page sets the full openGraph and
 * twitter objects here instead of relying on the root layout.
 */
export function pageMetadata({
  title,
  description,
  path,
  type = 'website',
}: PageMetadataInput): Metadata {
  // Generated by src/app/opengraph-image.tsx. Referenced explicitly because a
  // page-level openGraph object does not inherit the root file-based image.
  const image = { url: '/opengraph-image', width: 1200, height: 630, alt: siteConfig.name };
  return {
    title: { absolute: title },
    description,
    alternates: { canonical: path },
    openGraph: {
      type,
      title,
      description,
      url: path,
      siteName: siteConfig.name,
      locale: siteConfig.locale,
      images: [image],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [image],
    },
  };
}

/** "{Page} | Harivin Multispecialty Homeo Clinic" */
export const titleWithSite = (page: string) => `${page} | ${siteConfig.name}`;

// ---------------------------------------------------------------------------
// JSON-LD
// ---------------------------------------------------------------------------

export function medicalClinicJsonLd() {
  const { contact, doctor } = siteConfig;
  return {
    '@context': 'https://schema.org',
    '@type': 'MedicalClinic',
    '@id': `${absoluteUrl('/')}#clinic`,
    name: siteConfig.name,
    description: siteConfig.description,
    url: absoluteUrl('/'),
    image: absoluteUrl('/opengraph-image'),
    telephone: contact.phoneHref.replace('tel:', ''),
    email: contact.email,
    address: {
      '@type': 'PostalAddress',
      streetAddress: contact.address.street,
      addressLocality: contact.address.city,
      addressRegion: contact.address.region,
      postalCode: contact.address.postalCode,
      addressCountry: contact.address.country,
    },
    openingHoursSpecification: contact.openingHours.map((h) => ({
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: h.days,
      opens: h.opens,
      closes: h.closes,
    })),
    employee: {
      '@type': 'Physician',
      name: doctor.name,
    },
  };
}

export interface Crumb {
  name: string;
  /** Path starting with "/". Omit for the current page. */
  href?: string;
}

export function breadcrumbJsonLd(crumbs: Crumb[], currentPath: string) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: crumbs.map((crumb, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: crumb.name,
      item: absoluteUrl(crumb.href ?? currentPath),
    })),
  };
}
