/**
 * Treatment categories and conditions: the single source of truth for the
 * Treatments mega-menu, category pages, condition pages and the sitemap.
 *
 * Do not import this file from pages or components. Go through
 * `src/lib/treatments.ts`, so the data source can later be swapped for a
 * database without touching any page.
 *
 * Content rules: use neutral wording ("Homoeopathic care for …", "Conditions
 * we see"). Never use "cure", "guaranteed", "permanent relief" or "100% safe".
 *
 * The `content` paragraphs are PLACEHOLDERS generated by `placeholderContent()`.
 * Replace them with text written or reviewed by the doctor before launch.
 */

const SITE_NAME = 'Harivin Multispecialty Homeo Clinic';

export type CategoryIcon =
  'lungs' | 'ear' | 'skin' | 'bone' | 'digestive' | 'women' | 'chronic' | 'child' | 'mind' | 'plus';

export interface CategoryRecord {
  slug: string;
  name: string;
  icon: CategoryIcon;
  /** One line, used on cards and in the mega-menu. */
  shortDescription: string;
  /** Intro paragraph at the top of the category page. */
  intro: string;
  seoTitle: string;
  seoDescription: string;
}

export interface ConditionRecord {
  slug: string;
  name: string;
  /**
   * Categories this condition is listed under. The FIRST one is the primary
   * category, used for breadcrumbs and "related conditions". A condition has
   * one canonical page however many categories it appears in.
   */
  categorySlugs: string[];
  shortDescription: string;
  /** Body paragraphs, rendered in order. */
  content: string[];
  seoTitle: string;
  seoDescription: string;
}

const seoTitle = (name: string) => `${name} – Homoeopathy Care | ${SITE_NAME}`;

export const categories: CategoryRecord[] = [
  {
    slug: 'allergy-respiratory',
    name: 'Allergy & Respiratory',
    icon: 'lungs',
    shortDescription: 'Allergies, asthma, recurring colds and sinus problems.',
    intro:
      'Allergies and breathing problems often follow a pattern, flaring up with the seasons, dust, certain foods or stress. Our homoeopathic approach looks at those patterns alongside your general health to plan individualised care for adults and children.',
    seoTitle: seoTitle('Allergy & Respiratory'),
    seoDescription:
      'Homoeopathic care for allergy, asthma, COPD, recurrent cold, sinusitis and tonsillitis at Harivin Multispecialty Homeo Clinic. Individualised treatment for all ages.',
  },
  {
    slug: 'ent',
    name: 'ENT',
    icon: 'ear',
    shortDescription: 'Ear, nose and throat complaints, including sinusitis and tonsillitis.',
    intro:
      'Ear, nose and throat complaints can keep returning and disturb sleep, work and school. After understanding your history and any examination findings, we plan homoeopathic care suited to you.',
    seoTitle: seoTitle('ENT'),
    seoDescription:
      'Homoeopathic care for ear problems, sinusitis and tonsillitis at Harivin Multispecialty Homeo Clinic. Gentle, individualised treatment for adults and children.',
  },
  {
    slug: 'skin-hair',
    name: 'Skin & Hair',
    icon: 'skin',
    shortDescription: 'Acne, eczema, psoriasis, hair fall and other skin and scalp concerns.',
    intro:
      'Skin and hair often reflect what is happening inside the body, including stress, hormones, digestion and diet. Homoeopathic care for skin and hair concerns considers these factors together rather than the skin alone.',
    seoTitle: seoTitle('Skin & Hair'),
    seoDescription:
      'Homoeopathic care for acne, eczema, psoriasis, dermatitis, fungal infection, warts, hair fall and dandruff at Harivin Multispecialty Homeo Clinic.',
  },
  {
    slug: 'bones-joints',
    name: 'Bones & Joints',
    icon: 'bone',
    shortDescription: 'Arthritis, gout, spondylitis and everyday joint pain.',
    intro:
      'Joint pain and stiffness can affect sleep, work and independence. Our homoeopathic care for bone and joint concerns is planned around your symptoms, daily routine and overall health, with practical advice on movement and diet.',
    seoTitle: seoTitle('Bones & Joints'),
    seoDescription:
      'Homoeopathic care for arthritis, osteoarthritis, gout, spondylitis and joint pain at Harivin Multispecialty Homeo Clinic. Individualised, supportive treatment.',
  },
  {
    slug: 'digestive-disorders',
    name: 'Digestive Disorders',
    icon: 'digestive',
    shortDescription: 'Acidity, reflux, ulcers and piles.',
    intro:
      'Digestive complaints are closely linked to eating habits, sleep and stress. We look at all of these when planning homoeopathic care, and offer guidance on routine and diet along with treatment.',
    seoTitle: seoTitle('Digestive Disorders'),
    seoDescription:
      'Homoeopathic care for GERD, acidity, gastric ulcer and piles (hemorrhoids) at Harivin Multispecialty Homeo Clinic, with diet and lifestyle guidance.',
  },
  {
    slug: 'womens-health',
    name: 'Women’s Health',
    icon: 'women',
    shortDescription: 'Menstrual concerns, PCOD / PCOS, fibroids, fertility and menopause.',
    intro:
      'From the first period to menopause, women’s health needs change over time. We offer a private, unhurried consultation and homoeopathic care that considers physical and emotional wellbeing together.',
    seoTitle: seoTitle('Women’s Health'),
    seoDescription:
      'Homoeopathic care for menstrual problems, PCOD / PCOS, fibroid, leucorrhoea, infertility and menopause at Harivin Multispecialty Homeo Clinic.',
  },
  {
    slug: 'chronic-conditions',
    name: 'Chronic Conditions',
    icon: 'chronic',
    shortDescription: 'Supportive care for diabetes, blood pressure, thyroid and weight.',
    intro:
      'Long-term conditions need steady, ongoing care. Homoeopathy is offered here as supportive care alongside the medicines and monitoring advised by your treating doctor, never as a replacement for them.',
    seoTitle: seoTitle('Chronic Conditions'),
    seoDescription:
      'Supportive homoeopathic care for diabetes, hypertension, thyroid disorders and obesity at Harivin Multispecialty Homeo Clinic, alongside your regular treatment.',
  },
  {
    slug: 'childrens-health',
    name: 'Children’s Health',
    icon: 'child',
    shortDescription: 'Gentle care for allergies, colds, fever and developmental concerns.',
    intro:
      'Children need gentle care and a clinician who takes time to listen to them and their parents. We see children of all ages for recurring illnesses as well as developmental and behavioural concerns.',
    seoTitle: seoTitle('Children’s Health'),
    seoDescription:
      'Gentle homoeopathic care for children with allergy, asthma, recurrent cold, fever, ADHD and autism at Harivin Multispecialty Homeo Clinic.',
  },
  {
    slug: 'mental-health',
    name: 'Mental Health',
    icon: 'mind',
    shortDescription: 'Stress, anxiety, low mood, sleep and related concerns.',
    intro:
      'Emotional wellbeing affects every part of life. Our consultations give you time to talk openly, and homoeopathic care can be offered alongside counselling, therapy or medicines from your other doctors.',
    seoTitle: seoTitle('Mental Health'),
    seoDescription:
      'Homoeopathic care for stress, anxiety, depression, phobias, OCD and insomnia at Harivin Multispecialty Homeo Clinic. Confidential, individualised consultations.',
  },
  {
    slug: 'other-conditions',
    name: 'Other Conditions',
    icon: 'plus',
    shortDescription: 'Migraine, kidney stones, varicose veins and more.',
    intro:
      'We also see people with a range of other concerns. If you do not see your condition listed, please contact the clinic to ask whether a consultation would be appropriate.',
    seoTitle: seoTitle('Other Conditions'),
    seoDescription:
      'Homoeopathic care for migraine, kidney stone, varicose veins, autoimmune disorders, heart conditions and burns & injuries at Harivin Multispecialty Homeo Clinic.',
  },
];

/** Generic placeholder body text. Replace per condition before launch. */
function placeholderContent(phrase: string, note?: string): string[] {
  const paragraphs = [
    `At ${SITE_NAME}, homoeopathic care for ${phrase} begins with a detailed consultation. Along with your main symptoms, the doctor asks about your general health, sleep, appetite, emotional wellbeing and personal and family medical history, so that the remedy is chosen for you as an individual and not for the condition alone.`,
    'Your progress is reviewed at regular follow-up visits, and the remedy or dosage may be adjusted as things change. Many people continue the treatment prescribed by their other doctors while receiving homoeopathic care. Please bring a list of your current medicines and any recent reports to your first visit.',
    'How each person responds to treatment varies. If your symptoms are severe, getting worse, or new and unexplained, please see a doctor promptly for diagnosis.',
  ];
  return note ? [...paragraphs, note] : paragraphs;
}

interface ConditionInput {
  slug: string;
  name: string;
  categorySlugs: string[];
  shortDescription: string;
  /** How the name reads mid-sentence, if not simply lower-cased. */
  phrase?: string;
  /** Extra safety note appended to the content. */
  note?: string;
}

function condition({
  slug,
  name,
  categorySlugs,
  shortDescription,
  phrase,
  note,
}: ConditionInput): ConditionRecord {
  return {
    slug,
    name,
    categorySlugs,
    shortDescription,
    content: placeholderContent(phrase ?? name.toLowerCase(), note),
    seoTitle: seoTitle(name),
    seoDescription: `${shortDescription} Book a consultation at ${SITE_NAME}.`,
  };
}

/**
 * Order matters: a category lists its conditions in the order they appear here.
 */
export const conditions: ConditionRecord[] = [
  // Allergy & Respiratory / ENT
  condition({
    slug: 'allergy',
    name: 'Allergy',
    categorySlugs: ['allergy-respiratory', 'childrens-health'],
    shortDescription:
      'Individualised homoeopathic care for recurring allergic symptoms such as sneezing, a runny nose, itchy eyes or skin reactions.',
    phrase: 'allergies',
  }),
  condition({
    slug: 'asthma',
    name: 'Asthma',
    categorySlugs: ['allergy-respiratory', 'childrens-health'],
    shortDescription:
      'Supportive homoeopathic care for asthma, offered alongside your prescribed inhalers and the advice of your treating doctor.',
    note: 'Please do not stop or reduce inhalers or other asthma medicines without advice from your treating doctor. If you have a severe asthma attack, seek emergency medical care straight away.',
  }),
  condition({
    slug: 'copd',
    name: 'COPD',
    categorySlugs: ['allergy-respiratory'],
    shortDescription:
      'Homoeopathic care that complements the ongoing medical management of chronic obstructive pulmonary disease (COPD).',
    phrase: 'COPD',
    note: 'Continue your prescribed inhalers and oxygen as advised. Sudden or severe breathlessness, chest pain or bluish lips need emergency medical care.',
  }),
  condition({
    slug: 'recurrent-cold',
    name: 'Recurrent Cold',
    categorySlugs: ['allergy-respiratory', 'childrens-health'],
    shortDescription:
      'Homoeopathic care for adults and children who catch colds frequently, with attention to overall health and immunity.',
    phrase: 'frequent colds',
  }),
  condition({
    slug: 'ear-problems',
    name: 'Ear Problems',
    categorySlugs: ['ent'],
    shortDescription:
      'Homoeopathic care for common ear complaints such as recurring ear infections, discharge and blocked ears, after a proper medical examination.',
    note: 'Sudden hearing loss, severe ear pain, or ear discharge with fever should be examined by a doctor without delay.',
  }),
  condition({
    slug: 'sinusitis',
    name: 'Sinusitis',
    categorySlugs: ['allergy-respiratory', 'ent'],
    shortDescription:
      'Homoeopathic care for recurring sinus congestion, facial pressure, headaches and post-nasal drip associated with sinusitis.',
  }),
  condition({
    slug: 'tonsillitis',
    name: 'Tonsillitis',
    categorySlugs: ['allergy-respiratory', 'ent'],
    shortDescription:
      'Homoeopathic care for people, especially children, who have repeated episodes of sore throat and swollen tonsils.',
    note: 'A high fever, drooling, or difficulty swallowing or breathing needs prompt medical attention.',
  }),

  // Skin & Hair
  condition({
    slug: 'acne',
    name: 'Acne',
    categorySlugs: ['skin-hair'],
    shortDescription:
      'Homoeopathic care for acne and pimples, considering factors such as hormones, diet, stress and skin type.',
  }),
  condition({
    slug: 'eczema',
    name: 'Eczema',
    categorySlugs: ['skin-hair'],
    shortDescription:
      'Individualised homoeopathic care for eczema, focusing on itching, dryness and the pattern of flare-ups.',
  }),
  condition({
    slug: 'psoriasis',
    name: 'Psoriasis',
    categorySlugs: ['skin-hair'],
    shortDescription:
      'Homoeopathic care for psoriasis, a long-term skin condition that tends to come and go, with attention to triggers such as stress.',
  }),
  condition({
    slug: 'dermatitis',
    name: 'Dermatitis',
    categorySlugs: ['skin-hair'],
    shortDescription:
      'Homoeopathic care for skin inflammation and irritation, including contact and allergic dermatitis.',
  }),
  condition({
    slug: 'fungal-infection',
    name: 'Fungal Infection',
    categorySlugs: ['skin-hair'],
    shortDescription:
      'Homoeopathic care for recurring fungal skin infections, along with practical advice on hygiene and prevention.',
    phrase: 'fungal skin infections',
  }),
  condition({
    slug: 'warts',
    name: 'Warts',
    categorySlugs: ['skin-hair'],
    shortDescription:
      'Homoeopathic care for common warts on the hands, feet and other parts of the body.',
  }),
  condition({
    slug: 'hair-fall',
    name: 'Hair Fall',
    categorySlugs: ['skin-hair'],
    shortDescription:
      'Homoeopathic care for hair fall, taking into account nutrition, stress, hormones and scalp health.',
  }),
  condition({
    slug: 'dandruff',
    name: 'Dandruff',
    categorySlugs: ['skin-hair'],
    shortDescription: 'Homoeopathic care for persistent dandruff and an itchy, flaky scalp.',
  }),

  // Bones & Joints
  condition({
    slug: 'arthritis',
    name: 'Arthritis',
    categorySlugs: ['bones-joints'],
    shortDescription:
      'Homoeopathic care for joint pain, stiffness and swelling associated with different types of arthritis.',
  }),
  condition({
    slug: 'osteoarthritis',
    name: 'Osteoarthritis',
    categorySlugs: ['bones-joints'],
    shortDescription:
      'Supportive homoeopathic care for osteoarthritis, focusing on pain, stiffness and day-to-day mobility.',
  }),
  condition({
    slug: 'gout',
    name: 'Gout',
    categorySlugs: ['bones-joints'],
    shortDescription:
      'Homoeopathic care for gout, together with guidance on the diet and lifestyle factors that can trigger attacks.',
  }),
  condition({
    slug: 'spondylitis',
    name: 'Spondylitis',
    categorySlugs: ['bones-joints'],
    shortDescription:
      'Homoeopathic care for neck and back pain and stiffness associated with cervical and lumbar spondylitis.',
  }),
  condition({
    slug: 'joint-pain',
    name: 'Joint Pain',
    categorySlugs: ['bones-joints'],
    shortDescription:
      'Homoeopathic care for joint aches and pains, after an assessment to understand their cause.',
  }),

  // Digestive Disorders
  condition({
    slug: 'gerd',
    name: 'GERD',
    categorySlugs: ['digestive-disorders'],
    shortDescription:
      'Homoeopathic care for acidity, heartburn and reflux (GERD), along with advice on eating habits.',
    phrase: 'acidity and reflux (GERD)',
    note: 'Chest pain should never be assumed to be acidity. If you have chest pain, especially with breathlessness or sweating, seek emergency care immediately.',
  }),
  condition({
    slug: 'gastric-ulcer',
    name: 'Gastric Ulcer',
    categorySlugs: ['digestive-disorders'],
    shortDescription:
      'Homoeopathic care for gastric ulcers, offered alongside appropriate medical investigation and treatment.',
    phrase: 'gastric ulcers',
    note: 'Vomiting blood, black or tarry stools, or severe abdominal pain need urgent medical attention.',
  }),
  condition({
    slug: 'piles',
    name: 'Piles (Hemorrhoids)',
    categorySlugs: ['digestive-disorders'],
    shortDescription:
      'Homoeopathic care for piles (hemorrhoids), including discomfort, itching and bleeding, with dietary guidance.',
    note: 'Rectal bleeding should always be examined by a doctor to rule out other causes.',
  }),

  // Women's Health
  condition({
    slug: 'menstrual-problems',
    name: 'Menstrual Problems',
    categorySlugs: ['womens-health'],
    shortDescription:
      'Homoeopathic care for painful, irregular or heavy periods and premenstrual symptoms.',
  }),
  condition({
    slug: 'pcod-pcos',
    name: 'PCOD / PCOS',
    categorySlugs: ['womens-health'],
    shortDescription:
      'Homoeopathic care for PCOD / PCOS that considers cycles, weight, skin and emotional wellbeing together.',
    phrase: 'PCOD / PCOS',
  }),
  condition({
    slug: 'fibroid',
    name: 'Fibroid',
    categorySlugs: ['womens-health'],
    shortDescription:
      'Supportive homoeopathic care for women with uterine fibroids, alongside regular gynaecological follow-up.',
    phrase: 'uterine fibroids',
    note: 'Very heavy bleeding, severe pelvic pain or symptoms of anaemia need prompt review by a gynaecologist.',
  }),
  condition({
    slug: 'leucorrhoea',
    name: 'Leucorrhoea',
    categorySlugs: ['womens-health'],
    shortDescription:
      'Homoeopathic care for abnormal vaginal discharge (leucorrhoea), after an appropriate examination.',
  }),
  condition({
    slug: 'infertility',
    name: 'Infertility',
    categorySlugs: ['womens-health'],
    shortDescription:
      'Supportive homoeopathic care for couples facing difficulty conceiving, alongside fertility evaluation by a specialist.',
    phrase: 'couples facing difficulty conceiving',
  }),
  condition({
    slug: 'menopause',
    name: 'Menopause',
    categorySlugs: ['womens-health'],
    shortDescription:
      'Homoeopathic care for symptoms around menopause, such as hot flushes, disturbed sleep and mood changes.',
    phrase: 'menopausal symptoms',
  }),

  // Chronic Conditions
  condition({
    slug: 'diabetes',
    name: 'Diabetes',
    categorySlugs: ['chronic-conditions'],
    shortDescription:
      'Supportive homoeopathic care for people living with diabetes, alongside their prescribed medicines and regular monitoring.',
    phrase: 'people living with diabetes',
    note: 'Please continue your prescribed diabetes medicines or insulin and keep monitoring your blood sugar as advised by your treating doctor.',
  }),
  condition({
    slug: 'hypertension',
    name: 'Hypertension',
    categorySlugs: ['chronic-conditions'],
    shortDescription:
      'Supportive homoeopathic care for high blood pressure, alongside prescribed medication and lifestyle changes.',
    phrase: 'high blood pressure',
    note: 'Please continue your blood pressure medicines and regular check-ups as advised by your treating doctor.',
  }),
  condition({
    slug: 'thyroid-disorders',
    name: 'Thyroid Disorders',
    categorySlugs: ['chronic-conditions'],
    shortDescription:
      'Supportive homoeopathic care for thyroid conditions, with regular blood tests and follow-up with your treating doctor.',
    phrase: 'thyroid conditions',
    note: 'Please do not stop or change thyroid medication without advice from your treating doctor.',
  }),
  condition({
    slug: 'obesity',
    name: 'Obesity',
    categorySlugs: ['chronic-conditions'],
    shortDescription:
      'Homoeopathic care as part of a broader weight-management plan that includes diet, activity and sleep.',
    phrase: 'weight management',
  }),

  // Children's Health (Allergy, Asthma and Recurrent Cold are listed above)
  condition({
    slug: 'fever',
    name: 'Fever',
    categorySlugs: ['childrens-health'],
    shortDescription:
      'Homoeopathic care for children with fever, with clear guidance on when to seek urgent medical help.',
    phrase: 'children with fever',
    note: 'Seek urgent medical care if a child has a very high fever, a fit (seizure), unusual drowsiness, difficulty breathing, a rash that does not fade when pressed, or is under three months old with any fever.',
  }),
  condition({
    slug: 'adhd',
    name: 'ADHD',
    categorySlugs: ['childrens-health'],
    shortDescription:
      'Supportive homoeopathic care for children with attention and hyperactivity concerns, alongside assessment and support from specialists and teachers.',
    phrase: 'children with ADHD',
  }),
  condition({
    slug: 'autism',
    name: 'Autism',
    categorySlugs: ['childrens-health'],
    shortDescription:
      'Supportive homoeopathic care for children on the autism spectrum, as part of a wider plan that includes therapies and specialist guidance.',
    phrase: 'children on the autism spectrum',
  }),

  // Mental Health
  condition({
    slug: 'stress',
    name: 'Stress',
    categorySlugs: ['mental-health'],
    shortDescription: 'Homoeopathic care for the physical and emotional effects of ongoing stress.',
  }),
  condition({
    slug: 'anxiety',
    name: 'Anxiety',
    categorySlugs: ['mental-health'],
    shortDescription:
      'Homoeopathic care for anxiety, worry and related physical symptoms, alongside counselling where helpful.',
  }),
  condition({
    slug: 'depression',
    name: 'Depression',
    categorySlugs: ['mental-health'],
    shortDescription:
      'Supportive homoeopathic care for low mood and depression, alongside appropriate psychological and medical support.',
    phrase: 'low mood and depression',
    note: 'If you are having thoughts of harming yourself, please contact emergency services or a crisis helpline immediately. In India you can call the Tele-MANAS helpline on 14416.',
  }),
  condition({
    slug: 'phobias',
    name: 'Phobias',
    categorySlugs: ['mental-health'],
    shortDescription: 'Homoeopathic care for specific fears and phobias that affect daily life.',
  }),
  condition({
    slug: 'ocd',
    name: 'OCD',
    categorySlugs: ['mental-health'],
    shortDescription:
      'Supportive homoeopathic care for obsessive-compulsive symptoms, alongside psychological therapy where appropriate.',
    phrase: 'obsessive-compulsive disorder (OCD)',
  }),
  condition({
    slug: 'insomnia',
    name: 'Insomnia / Sleep Problems',
    categorySlugs: ['mental-health'],
    shortDescription:
      'Homoeopathic care for difficulty falling or staying asleep, together with practical advice on sleep habits.',
    phrase: 'insomnia and sleep problems',
  }),

  // Other Conditions
  condition({
    slug: 'migraine',
    name: 'Migraine',
    categorySlugs: ['other-conditions'],
    shortDescription:
      'Homoeopathic care for recurring migraine headaches, with attention to triggers and overall health.',
    note: 'A sudden, severe headache, or a headache with weakness, confusion or loss of vision, needs emergency medical care.',
  }),
  condition({
    slug: 'kidney-stone',
    name: 'Kidney Stone',
    categorySlugs: ['other-conditions'],
    shortDescription:
      'Supportive homoeopathic care for people with kidney stones, alongside imaging and advice from a urologist.',
    phrase: 'kidney stones',
    note: 'Severe pain, fever with pain, vomiting, or being unable to pass urine need emergency medical care.',
  }),
  condition({
    slug: 'varicose-veins',
    name: 'Varicose Veins',
    categorySlugs: ['other-conditions'],
    shortDescription:
      'Homoeopathic care for the aching, heaviness and swelling associated with varicose veins.',
  }),
  condition({
    slug: 'autoimmune-disorders',
    name: 'Autoimmune Disorders',
    categorySlugs: ['other-conditions'],
    shortDescription:
      'Supportive homoeopathic care for people with autoimmune conditions, alongside the care of their specialist.',
    phrase: 'autoimmune conditions',
    note: 'Please continue the treatment prescribed by your specialist and do not stop any medicines without their advice.',
  }),
  condition({
    slug: 'heart-conditions',
    name: 'Heart Conditions',
    categorySlugs: ['other-conditions'],
    shortDescription:
      'Supportive homoeopathic care for people with heart conditions, strictly alongside their cardiologist’s treatment.',
    phrase: 'people with heart conditions',
    note: 'Never stop or change heart medication without advice from your cardiologist. Chest pain, breathlessness or fainting need emergency medical care immediately.',
  }),
  condition({
    slug: 'burns-and-injuries',
    name: 'Burns & Injuries',
    categorySlugs: ['other-conditions'],
    shortDescription:
      'Supportive homoeopathic care during recovery from minor burns and injuries, after appropriate first aid and medical assessment.',
    phrase: 'recovery from minor burns and injuries',
    note: 'Serious burns and injuries need emergency medical treatment first.',
  }),
];
